spring:
  config:
    activate:
      on-profile: prod-server

  security:
    jwt:
      header: Authorization
      secret: ENC(65h2069y4sNrEcUWWCUBpN21Kl0Cef8XUS85jjld04p8T9iWTq6WF6k2o5lu4cfxLYdGI8FHV5T/drif0KLvj/QuEjF5LVNwzprqksewN9UPbvVJHeG5NUWE/8jGfKTQ56q0RaqBkiZQpYtT6VDZaA==)
      access-token-validity-in-seconds: 3600     # 1시간
      refresh-token-validity-in-seconds: 1_209_600  # 2주

  datasource:
    url: ENC(5vJHJq4MbDRt4KeGuFvNE289DKbsKTCnkqhKjLnprFvK11EGp68BaVqg/px+qm1IujcBHDmZf1RJ+9y3LpVCEPNRfVv9cio+rXVYHjvn1G6kT5QH1WBr7/UCguq+chU+TBq6QxYMdVkT4tGtA0SOfqvooqsk1dgDc4f9TUfmVLxiD3SFhfvhPfAm5aJMqN6X)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(mIXsC1y08iwYMAsrFZjei8HQiLhhMVcW3BbqG8isI5OFOJoR8ir2OiFQIrJR9uk8kuUO5Lx+0XWQ9E9TkMG7Rw==)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_PASSWORD}

server:
  port: ENC(jBBqJC00hA3ZZmVnfugq+FucDrJ0AZBrC2darLq5gOlFimO+h2zTgeUT3zBxTlgN)