spring:
  config:
    activate:
      on-profile: prod-server

  security:
    jwt:
      header: Authorization
      secret: ENC(65h2069y4sNrEcUWWCUBpN21Kl0Cef8XUS85jjld04p8T9iWTq6WF6k2o5lu4cfxLYdGI8FHV5T/drif0KLvj/QuEjF5LVNwzprqksewN9UPbvVJHeG5NUWE/8jGfKTQ56q0RaqBkiZQpYtT6VDZaA==)
      access-token-validity-in-seconds: 3600     # 1시간
      refresh-token-validity-in-seconds: 1_209_600  # 2주

  datasource:
    url: ENC(8+/bWefYmWQElrDSCzVahUY66cIjhf+6q+VduTzoMlSqHG69XJeXePFB9ew6W1x/8kqF00yMonCyBOKu36JGU8+MjiSqz/OyfWwMIFlK815V2u8Ginum82OhSHaba1DaBQi/nSgTiepZ0wYkULtc/KTO6t9a2GNHqPi5Z1POdjii5RwMfrbBNGxWlVcEAYGh)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 8team
    password: ENC(Az9xEfBQnEAca68JsA/KYmaZtT0ko9oGiLOG7d6qfKuc/ySwUGdJmmj0P1CuG2O7)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

  data:
    redis:
      port: ENC(wyPfla5qSG4+QZnMJrigZ18Cy4GU0J0dAgUDl2fMN4fJsSgPjVIxSUcapWhzWigA)
      host: ENC(N41vph2odUQOK9pSYY/MPeTq5uohYLaDusaHc+Rdyf8Nv2RhMRarBtK0/ruVQo6V)

  logging:
    level:
      org.springframework.data.elsasticsearch.client.WIRE: TRACE

  elasticsearch:
    host: ENC(3CXNdPPQ0Rayk+XAR81xg55lnmWEJUVfOC4Ii/aS8Z+wNVRxZJkKzCYtOXCWiOYL)

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_PASSWORD}

coolsms:
  api:
    key: ENC(ITqSIpefSrAWYUtfl6zaZAxnNCSJIoLJno7wp3qMXukfQzxFxZCYChyghwUlNtH2pYCiXV2t4X/6wOzzA/2s9w==)
    secret: ENC(hSZH9A9f2cMQ/uHL/bn2aQDJN3PYSwsJeJ3FtBImNZoYozbltZVSsdWxlLUd4u+6rsRkzpTY6x0WcbbvR7vNKh6ltmLfddCOhQ5tzoEQ/KA=)
  from:
    contact: ENC(DjQI+YpK3+2NICV3jFYJPjrjY3q7KEc8sSpOBIUQ3qpFq02LkAI9CKd6qj4eZp1l)

server:
  state: blue
  port: ENC(jBBqJC00hA3ZZmVnfugq+FucDrJ0AZBrC2darLq5gOlFimO+h2zTgeUT3zBxTlgN)