name: BE-final prod deploy

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  if-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run : |
          chmod +x ./gradlew
          ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Docker
        run : docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final final-api

      - name: Docker push
        run : docker push ${{ secrets.DOCKERHUB_USERNAME }}/final:latest

  deploy:
    needs: if-merge
    runs-on: ubuntu-latest
    steps:
      - name: Execute Server Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ env.STOPPED_IP }}
          key: ${{ secrets.BLUE_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker stop prod
            sudo docker rm prod
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/final
            sudo docker-compose up -d
