name: BE-final prod deploy

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  if-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up application-prod.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          jasypt.encryptor.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Build with Gradle
        run : |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build with Docker
        run : docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow .

      - name: Docker push
        run : docker push ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow:latest

  deploy:
    needs: if-merge
    runs-on: ubuntu-latest
    steps:
      - name: Execute Server Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker stop prod || true
            sudo docker rm prod || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
            sudo docker run --name neuroflow -d -p ${{ secrets.PORT_MAPPING }} ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
            sudo docker system prune -f
