name: Java CI with Gradle V0.1

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up application-prod.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          jasypt.encryptor.password: ${{ secrets.JASYPT_PASSWORD }}

      - name: Test with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
